// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyqAiultYZzwcoRfQhNKRiCG3DuEBEsd8',
    appId: '1:1039275246750:web:ee61d0b254a2697a3e278f',
    messagingSenderId: '1039275246750',
    projectId: 'backendlogsign',
    authDomain: 'backendlogsign.firebaseapp.com',
    databaseURL: 'https://backendlogsign-default-rtdb.firebaseio.com',
    storageBucket: 'backendlogsign.appspot.com',
    measurementId: 'G-C9R69XEVH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyqAiultYZzwcoRfQhNKRiCG3DuEBEsd8',
    appId: '1:1039275246750:android:ee61d0b254a2697a3e278f',
    messagingSenderId: '1039275246750',
    projectId: 'backendlogsign',
    databaseURL: 'https://backendlogsign-default-rtdb.firebaseio.com',
    storageBucket: 'backendlogsign.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyqAiultYZzwcoRfQhNKRiCG3DuEBEsd8',
    appId: '1:1039275246750:ios:ee61d0b254a2697a3e278f',
    messagingSenderId: '1039275246750',
    projectId: 'backendlogsign',
    databaseURL: 'https://backendlogsign-default-rtdb.firebaseio.com',
    storageBucket: 'backendlogsign.appspot.com',
    iosBundleId: 'com.example.parishonersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyqAiultYZzwcoRfQhNKRiCG3DuEBEsd8',
    appId: '1:1039275246750:macos:ee61d0b254a2697a3e278f',
    messagingSenderId: '1039275246750',
    projectId: 'backendlogsign',
    databaseURL: 'https://backendlogsign-default-rtdb.firebaseio.com',
    storageBucket: 'backendlogsign.appspot.com',
    iosBundleId: 'com.example.parishonersApp',
  );
} 